config/routes.rb
Rails.application.routes.draw do

  resources :wholesalers do
    resources :batches, only: [:index]
    resources :offers, only: [:index, :edit, :update], controller: 'wholesalers/offers'
  end

  resources :batches, only: [:index]

  resources :batches

  resources :manufacturers do
    resources :batches do
      resources :offers, only: [:new, :create, :index, :destroy]
    end
    resources :offers, only: [:index], controller: 'manufacturers/offers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'batches#index'
end

app/models/wholesaler.rb
class Wholesaler < ApplicationRecord
  has_many :offers
  has_many :batches, through: :offers
end

app/controllers/wholesalers/offers_controller.rb
module Wholesalers
  class OffersController < ApplicationController
    before_action :set_offer, only: [:edit, :update]
    before_action :set_wholesaler


    def edit
    end

    def update
      #logger.debug "\n\nDEBUG: #{@wholesaler.inspect}\n\n"
      respond_to do |format|
        if @offer.update(offer_params)
          format.html { redirect_to wholesaler_path(@offer.wholesaler), notice: 'Offer was successfully updated.' }
          format.json { render :show, status: :ok, location: @offer }
        else
          format.html { render :edit }
          format.json { render json: @offer.errors, status: :unprocessable_entity }
        end
      end
    end

    private

    def set_offer
      @offer = Offer.find(params[:id])
    end

    def set_wholesaler
      @wholesaler = Wholesaler.find(params[:wholesaler_id])
    end

    def offer_params
      params.require(:offer).permit(:batch_id, :wholesaler_id, :amount, :accepted, :ignored)
    end
  end
end

app/controllers/wholesalers_controller.rb
class WholesalersController < ApplicationController
  before_action :set_wholesaler, only: [:show, :edit, :update, :destroy]

  # GET /wholesalers
  # GET /wholesalers.json
  def index
    @wholesalers = Wholesaler.all
  end

  # GET /wholesalers/1
  # GET /wholesalers/1.json
  def show
  end

  # GET /wholesalers/new
  def new
    @wholesaler = Wholesaler.new
  end

  # GET /wholesalers/1/edit
  def edit
  end

  # POST /wholesalers
  # POST /wholesalers.json
  def create
    @wholesaler = Wholesaler.new(wholesaler_params)

    respond_to do |format|
      if @wholesaler.save
        format.html { redirect_to @wholesaler, notice: 'Wholesaler was successfully created.' }
        format.json { render :show, status: :created, location: @wholesaler }
      else
        format.html { render :new }
        format.json { render json: @wholesaler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wholesalers/1
  # PATCH/PUT /wholesalers/1.json
  def update
    respond_to do |format|
      if @wholesaler.update(wholesaler_params)
        format.html { redirect_to @wholesaler, notice: 'Wholesaler was successfully updated.' }
        format.json { render :show, status: :ok, location: @wholesaler }
      else
        format.html { render :edit }
        format.json { render json: @wholesaler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wholesalers/1
  # DELETE /wholesalers/1.json
  def destroy
    @wholesaler.destroy
    respond_to do |format|
      format.html { redirect_to wholesalers_url, notice: 'Wholesaler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wholesaler
      @wholesaler = Wholesaler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wholesaler_params
      params.require(:wholesaler).permit(:name)
    end
end

app/helpers/wholesalers_helper.rb
module WholesalersHelper
end

app/views/wholesalers/_form.html.erb
<%= form_for(wholesaler) do |f| %>
  <% if wholesaler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wholesaler.errors.count, "error") %> prohibited this wholesaler from being saved:</h2>

      <ul>
      <% wholesaler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wholesalers/edit.html.erb
<h1>Editing Wholesaler</h1>

<%= render 'form', wholesaler: @wholesaler %>

<%= link_to 'Show', @wholesaler %> |
<%= link_to 'Back', wholesalers_path %>

app/views/wholesalers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wholesalers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wholesalers.each do |wholesaler| %>
      <tr>
        <td><%= link_to wholesaler.name, wholesaler %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wholesaler', new_wholesaler_path %>

app/views/wholesalers/new.html.erb
<h1>New Wholesaler</h1>

<%= render 'form', wholesaler: @wholesaler %>

<%= link_to 'Back', wholesalers_path %>

app/views/wholesalers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wholesaler.name %>
</p>

<h2>Available Batches</h2>
<table>
  <thead>
    <tr>
      <th> Description</th>
      <th> Amount </th>
      <th> Expiry </th>
    </tr>
  </thead>
   <tbody>
    <% @wholesaler.offers.each do |offer| %>
      <% unless offer.ignored %>
        <tr>
          <td><%= link_to offer.batch.description, edit_wholesaler_offer_path(offer.wholesaler, offer) %></td>
          <td>
            <%= offer.amount ? '$' + offer.amount.to_s : '$0' %></td>
          <td><%= offer.batch.expired? ? "Batch expired" : offer.batch.time_remaining %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to 'Edit', edit_wholesaler_path(@wholesaler) %> |
<%= link_to 'Back', wholesalers_path %>