config/routes.rb
Rails.application.routes.draw do

  resources :wholesalers do
    resources :batches, only: [:index]
    resources :offers, only: [:index, :edit, :update], controller: 'wholesalers/offers'
  end

  resources :batches, only: [:index]

  resources :batches

  resources :manufacturers do
    resources :batches do
      resources :offers, only: [:new, :create, :index, :destroy]
    end
    resources :offers, only: [:index], controller: 'manufacturers/offers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'batches#index'
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :batch
  belongs_to :wholesaler
  validates :amount, presence: true, :numericality =>  {:greater_than_or_equal_to => 0}
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_batch
  before_action :set_manufacturer
  before_action :set_wholesaler
  before_action :set_wholesalers
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    set_wholesalers
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to :back, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new}
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  def update
    #logger.debug "\n\nDEBUG: #{@wholesaler.inspect}\n\n"
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to wholesaler_offer_path(@wholesaler, @offer), notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = Offer.find(params[:id])
  end

  def set_batch
    @batch = Batch.find_by(id: params[:batch_id])
  end

  def set_manufacturer
    @manufacturer = Manufacturer.find_by(id: @batch.manufacturer_id)
  end

  def set_wholesaler
    @wholesaler = Wholesaler.find(params[:wholesaler_id]) if params[:wholesaler_id]
  end

  def set_wholesalers
    @selected_wholesalers = []       #wholesalers where the list of offer_ids includes this one
    Wholesaler.all.each do |wholesaler|
      @selected_wholesalers << wholesaler if wholesaler.batch_ids.include?(@batch.id)
    end
    @unselected_wholesalers = Wholesaler.all - @selected_wholesalers
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def offer_params
    params.require(:offer).permit(:batch_id, :wholesaler_id, :amount, :accepted, :ignored)
  end
end

app/controllers/wholesalers/offers_controller.rb
module Wholesalers
  class OffersController < ApplicationController
    before_action :set_offer, only: [:edit, :update]
    before_action :set_wholesaler


    def edit
    end

    def update
      #logger.debug "\n\nDEBUG: #{@wholesaler.inspect}\n\n"
      respond_to do |format|
        if @offer.update(offer_params)
          format.html { redirect_to wholesaler_path(@offer.wholesaler), notice: 'Offer was successfully updated.' }
          format.json { render :show, status: :ok, location: @offer }
        else
          format.html { render :edit }
          format.json { render json: @offer.errors, status: :unprocessable_entity }
        end
      end
    end

    private

    def set_offer
      @offer = Offer.find(params[:id])
    end

    def set_wholesaler
      @wholesaler = Wholesaler.find(params[:wholesaler_id])
    end

    def offer_params
      params.require(:offer).permit(:batch_id, :wholesaler_id, :amount, :accepted, :ignored)
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for([@manufacturer, @batch]) do |f| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :batch_id %>
    <%= f.text_field :batch_id %>
  </div>

  <div class="field">
    <%= f.label :wholesaler_id %>
    <%= f.text_field :wholesaler_id %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :accepted %>
    <%= f.check_box :accepted %>
  </div>

  <div class="field">
    <%= f.label :ignored %>
    <%= f.check_box :ignored %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <th>Batch</th>
      <th>Wholesaler</th>
      <th>Amount</th>
      <th>Accepted</th>
      <th>Ignored</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.batch %></td>
        <td><%= offer.wholesaler %></td>
        <td><%= offer.amount %></td>
        <td><%= offer.accepted %></td>
        <td><%= offer.ignored %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% #link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<div id="wrapper">
  <div id="first">
    <h2> Wholesalers</h2>
    <table>
      <thead>
      <tr>
        <th> Wholesaler </th>
        <th> Distance (km) </th>
        <th> Add</th>
      </tr>
      </thead>
      <tbody>
      <% @unselected_wholesalers.each do |wholesaler| %>
          <tr>
            <td><%=wholesaler.name %></td>
            <td><%= @batch.wholesaler_distance(wholesaler).round(1) %></td>
            <td><%= button_to '+', action: :create, params: {:offer => {:batch_id => @batch.id, :wholesaler_id => wholesaler.id, amount: 0}} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <div id="second">
    <h2>Selected Wholesalers</h2>
    <table>
      <thead>
      <tr>
        <th> Wholesaler </th>
        <th> Distance (km) </th>
        <th> Remove</th>
      </tr>
      </thead>
      <tbody>
      <% @selected_wholesalers.each do |wholesaler| %>
      <% @offer = @batch.offers.find_by(wholesaler_id: wholesaler.id) %>
          <tr>
            <td><%=wholesaler.name %></td>
            <td><%= @batch.wholesaler_distance(wholesaler).round(1) %></td>
            <td><%= button_to '-', manufacturer_batch_offer_path(@manufacturer, @batch, @offer), method: :delete, data: { wholesaler_id: wholesaler.id, confirm: 'Are you sure?' } %></td>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= link_to 'Back', manufacturer_batches_path(@manufacturer) %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Batch:</strong>
  <%= @offer.batch %>
</p>

<p>
  <strong>Wholesaler:</strong>
  <%= @offer.wholesaler %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @offer.amount %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @offer.accepted %>
</p>

<p>
  <strong>Ignored:</strong>
  <%= @offer.ignored %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>