config/routes.rb
Rails.application.routes.draw do

  resources :wholesalers do
    resources :batches, only: [:index]
    resources :offers, only: [:index, :edit, :update], controller: 'wholesalers/offers'
  end

  resources :batches, only: [:index]

  resources :batches

  resources :manufacturers do
    resources :batches do
      resources :offers, only: [:new, :create, :index, :destroy]
    end
    resources :offers, only: [:index], controller: 'manufacturers/offers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'batches#index'
end

app/models/batch.rb
require 'action_view'
include ActionView::Helpers::DateHelper

class Batch < ApplicationRecord
  belongs_to :manufacturer
  has_many :offers
  has_many :wholesalers, through: :offers
  validates :quantity, presence: true, :numericality =>  {:greater_than => 0}
  validates :fabric, presence: true
  validates :color, presence: true


  def self.not_expired
    where("created_at < ?", Time.now.utc - 7.days)
  end

  def expired?
    time_elapsed >= 7*24*60*60
  end



  def time_elapsed
    Time.now.utc - created_at
  end

  def time_remaining
    distance_of_time_in_words(7*24*60*60 - time_elapsed)
  end

  def description
    "x#{quantity} - #{fabric}, #{color}"
  end

  def highest_current_offer
    offers.order(amount: :desc).first
  end

  def accepted_offer
    offers.where(accepted: true).first
  end

  def wholesaler_distance(wholesaler)
    Geocoder::Calculations.distance_between([manufacturer.latitude,manufacturer.longitude], [wholesaler.latitude,wholesaler.longitude])
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: [:show, :edit, :update, :destroy]
  before_action :set_manufacturer

  # GET /batches
  # GET /batches.json
  def index
    # binding.pry-remote
    @batches = Batch.all
  end

  # GET /batches/1
  # GET /batches/1.json
  def show

  end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches
  # POST /batches.json
  def create
    @batch = Batch.new(batch_params)
    @batch.manufacturer_id = @manufacturer.id

    respond_to do |format|
      if @batch.save
        format.html { redirect_to [@batch.manufacturer, @batch], notice: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1
  # PATCH/PUT /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to @batch, notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch.destroy
    respond_to do |format|
      format.html { redirect_to batches_url, notice: 'Batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      @batch = Batch.find(params[:id])
    end

    def set_manufacturer
      @manufacturer = Manufacturer.find_by(id: params[:manufacturer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batch_params
      params.require(:batch).permit(:manufacturer_id, :quantity, :fabric, :color)
    end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.erb
<%= form_for([@manufacturer, @batch]) do |f| %>
  <% if batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manufacturer_id %>
    <%= @manufacturer.name %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :fabric %>
    <%= f.text_field :fabric %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Batches</h1>

<table>
  <thead>
    <tr>
      <th>Manufacturer</th>
      <th>Quantity</th>
      <th>Fabric</th>
      <th>Color</th>
      <th>Expiry</th>
      <th>Highest Bid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.manufacturer.name %></td>
        <td><%= batch.quantity %></td>
        <td><%= batch.fabric %></td>
        <td><%= batch.color %></td>
        <td><%= batch.expired? ? "Expired": batch.time_remaining %> </td>
        <td><%= batch.highest_current_offer.nil? ? 'No offers made': '$' + batch.highest_current_offer.amount.to_s %></td>
        <td><%= link_to 'Show', manufacturer_batch_path(batch.manufacturer, batch) %></td>
        <td><%= link_to 'Edit', edit_manufacturer_batch_path(batch.manufacturer, batch) %></td>
        <td><%= link_to 'Destroy', manufacturer_batch_path(batch.manufacturer, batch), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Back', manufacturer_batches_path(@manufacturer) %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manufacturer:</strong>
  <%= @batch.manufacturer.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @batch.quantity %>
</p>

<p>
  <strong>Fabric:</strong>
  <%= @batch.fabric %>
</p>

<p>
  <strong>Color:</strong>
  <%= @batch.color %>
</p>
 <%#show all offers on this batch
 wholesaler name  amount updated at%>
<h2>Offers</h2>
<table>
<thead>
  <tr>
    <th> Wholesaler</th>
    <th> Amount</th>
    <th> Date Updated</th>
  </tr>
</thead>
 <tbody>
    <% @batch.offers.each do |batch_offer| %>
        <tr>
        <td><%= batch_offer.wholesaler.name %></td>
        <td> <%= batch_offer.amount%>
        <td><%= batch_offer.updated_at.to_date%></td>
      </tr>
      <%end%>
  </tbody>
</table>


<%= link_to 'Edit', edit_manufacturer_batch_path(@batch) %> |
<%= link_to 'Back',   manufacturer_batches_path(@manufacturer) %>
<%= link_to 'Send Batch to Wholesalers', new_manufacturer_batch_offer_path(@manufacturer, @batch) %>