config/routes.rb
Rails.application.routes.draw do

  resources :wholesalers do
    resources :batches, only: [:index]
    resources :offers, only: [:index, :edit, :update], controller: 'wholesalers/offers'
  end

  resources :batches, only: [:index]

  resources :batches

  resources :manufacturers do
    resources :batches do
      resources :offers, only: [:new, :create, :index, :destroy]
    end
    resources :offers, only: [:index], controller: 'manufacturers/offers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'batches#index'
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :batches
  has_many :offers, through: :batches

end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :set_manufacturer, only: [:show, :edit, :update, :destroy]

  # GET /manufacturers
  # GET /manufacturers.json
  def index
    @manufacturers = Manufacturer.all
  end

  # GET /manufacturers/1
  # GET /manufacturers/1.json
  def show
  end

  # GET /manufacturers/new
  def new
    @manufacturer = Manufacturer.new
  end

  # GET /manufacturers/1/edit
  def edit
  end

  # POST /manufacturers
  # POST /manufacturers.json
  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    respond_to do |format|
      if @manufacturer.save
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully created.' }
        format.json { render :show, status: :created, location: @manufacturer }
      else
        format.html { render :new }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /manufacturers/1
  # PATCH/PUT /manufacturers/1.json
  def update
    respond_to do |format|
      if @manufacturer.update(manufacturer_params)
        format.html { redirect_to @manufacturer, notice: 'Manufacturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @manufacturer }
      else
        format.html { render :edit }
        format.json { render json: @manufacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufacturers/1
  # DELETE /manufacturers/1.json
  def destroy
    @manufacturer.destroy
    respond_to do |format|
      format.html { redirect_to manufacturers_url, notice: 'Manufacturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manufacturer_params
      params.require(:manufacturer).permit(:name)
    end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/manufacturers/_form.html.erb
<%= form_for(manufacturer) do |f| %>
  <% if manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manufacturer.errors.count, "error") %> prohibited this manufacturer from being saved:</h2>

      <ul>
      <% manufacturer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manufacturers/edit.html.erb
<h1>Editing Manufacturer</h1>

<%= render 'form', manufacturer: @manufacturer %>

<%= link_to 'Show', @manufacturer %> |
<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manufacturers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manufacturers.each do |manufacturer| %>
      <tr>

        <td><%= link_to manufacturer.name, manufacturer %></td>
        <%#<td><%= link_to 'Edit', edit_manufacturer_path(manufacturer) %></td>
        <%#<td><%= link_to 'Destroy', manufacturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manufacturer', new_manufacturer_path %>

app/views/manufacturers/new.html.erb
<h1>New Manufacturer</h1>

<%= render 'form', manufacturer: @manufacturer %>

<%= link_to 'Back', manufacturers_path %>

app/views/manufacturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manufacturer.name %>
</p>
<div>

<h2>Active Batches</h2>
<% unless @manufacturer.batches.empty? %>
  <table>

  <thead>
  <tr>
    <th> Description</th>
    <th> Current highest </th>
    <th> Expiry </th>
  </tr>
  </thead>
  <tbody>
    <% @manufacturer.batches.not_expired.each do |batch| %>
      <tr>
        <td><%= link_to batch.description, manufacturer_batch_path(batch.manufacturer, batch) %></td>
        <td>
          <% if batch.highest_current_offer && batch.highest_current_offer.amount > 0 %>
            $<%= batch.highest_current_offer.amount %> - <%= batch.highest_current_offer.wholesaler.name%>
          <% else %>
            There are no current offers for this batch.
          <% end %>
        </td>
        <td><%= batch.time_remaining %></td>
      </tr>
  <% end %>
  </tbody>
 </table>
<%end%>
</div>
<div>
<h2> Expired Batches</h2>
<table>
<thead>
<tr>
  <th> Description</th>
  <th> Winner</th>
  <th> Amount</th>
  <th> Date Completed </th>
  </tr>
  </thead>
  <tbody>
  <% @manufacturer.batches.each do |batch| %>
    <% if batch.expired? %>
       <tr>
       <td><%= batch.description %></td>
       <td><%= batch.accepted_offer.name %></td>
       <td><%= batch.accepted_offer.amount %></td>
       <td><%= "It was completed on this day"%></td>
       </tr>
    <% end %>
  <%end%>
   </tbody>
</table>
</div>
<br>
<%# need to make two tables 1 is for active batches- 2nd is for expired batches%>

<%= link_to 'Edit', edit_manufacturer_path(@manufacturer) %> |
<%= link_to 'Back', manufacturers_path %> |
<%= link_to 'Delete', @manufacturer, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'New Batch', new_manufacturer_batch_path(@manufacturer) %>